version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./app:/app/app
      - ./plusvans.db:/app/plusvans.db

volumes:
  sqlite_data:
